sudo: required
services:
  - docker

before_install:
  - docker build -t firatbezir/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true firatbezir/react-test npm run test

after_success:
  - docker build -t firatbezir/multi-client ./client
  - docker build -t firatbezir/multi-nginx ./nginx
  - docker build -t firatbezir/multi-server ./server
  - docker build -t firatbezir/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push firatbezir/multi-client
  - docker push firatbezir/multi-nginx
  - docker push firatbezir/multi-server
  - docker push firatbezir/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'multicontainer-docker'
  env: 'Multicontainer-docker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-615299743652'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY