sudo: required
services:
  - docker

before_install:
  - docker build -t firatbezir/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e firatbezir/react-test npm test 

after_success:
  - docker build -t firatbezir/multi-client ./client
  - docker build -t firatbezir/multi-nginx ./nginx
  - docker build -t firatbezir/multi-server ./server
  - docker build -t firatbezir/multi-worker ./worker
